import Link from "next/link";
import "./luana.css";
/* eslint-disable @next/next/no-img-element -- local optimized brand assets */
const INSTAGRAM="https://www.instagram.com/luanaabreunutri/";
const DOCTORALIA="https://www.doctoralia.com.br/luana-abreu/nutricionista/fortaleza?saasonly=true";
const WHATSAPP="https://wa.me/558596840106?text=Ol%C3%A1%21%20Gostaria%20de%20saber%20mais%20sobre%20o%20atendimento%20com%20Luana%20Abreu.";
const Insta=({dark=false}:{dark?:boolean})=><img src={"/icons/instagram-"+(dark?"dark":"light")+".png"} alt="" width="17" height="17"/>;
const Whats=()=><img src="/icons/whatsapp-light.png" alt="" width="18" height="18"/>;
export default function LuanaAbreuPage(){return <main className="la-page">
<header className="la-header"><a className="la-brand" href="#inicio"><img src="/luana/sublogo-gold.png" alt="Luana Abreu Nutricionista"/></a><nav><a href="#abordagem">Abordagem</a><a href="#atuacao">Atuação</a><a href="#sobre">Luana</a><a href="#contato">Contato</a></nav><a className="la-header-cta" href={DOCTORALIA} target="_blank" rel="noreferrer">Agendar consulta</a><details className="la-menu"><summary aria-label="Abrir menu"><span/><span/></summary><nav><a href="#abordagem">Abordagem</a><a href="#atuacao">Atuação</a><a href="#sobre">Luana</a><a href="#contato">Contato</a></nav></details></header>
<section className="la-hero" id="inicio"><div className="la-hero-copy"><p className="la-kicker">Nutricionista · CRN11 20550/P</p><h1>Nutrição que cabe<br/>na sua <em>vida.</em></h1><p className="la-lead">Acolhimento, estratégia e escolhas possíveis para construir saúde com mais leveza e constância.</p><div className="la-actions"><a className="la-button la-gold" href={DOCTORALIA} target="_blank" rel="noreferrer">Agendar consulta</a><a className="la-text-link" href="#abordagem">Conhecer a abordagem ↓</a></div></div><div className="la-hero-image"><img src="/luana/luana-abreu.webp" alt="Nutricionista Luana Abreu em seu consultório"/><div><span>Fortaleza - CE</span><span>Atendimento online</span></div></div></section>
<section className="la-manifesto la-section" id="abordagem"><p className="la-label">01 - Abordagem</p><div><h2>O plano precisa respeitar<br/>quem você <em>é.</em></h2><p className="la-large">Antes de orientar escolhas, é preciso compreender sua rotina, preferências, dificuldades e objetivos.</p></div><p className="la-support">A consulta é construída com escuta ativa e individualização para transformar recomendações em hábitos possíveis de sustentar.</p></section>
<section className="la-principles la-wine"><h2>Leveza não é falta<br/>de <em>direção.</em></h2><div className="la-principles-copy"><p>Escuta, individualização e constância orientam cada acompanhamento. A proposta é compreender sua realidade para construir escolhas alimentares possíveis, que respeitem suas preferências e possam ser sustentadas ao longo do tempo.</p></div></section>
<section className="la-areas la-section" id="atuacao"><div className="la-heading"><p className="la-label">03 - Atuação</p><h2>Objetivos reais.<br/><em>Estratégias possíveis.</em></h2></div><div className="la-grid"><article><span>01</span><h3>Emagrecimento saudável</h3><p>Organização alimentar com foco em saúde, consistência e relação equilibrada com a comida.</p></article><article><span>02</span><h3>Saúde intestinal</h3><p>Orientação nutricional individualizada a partir da rotina e das necessidades identificadas.</p></article><article><span>03</span><h3>Hipertrofia</h3><p>Alimentação alinhada à rotina de treino e aos objetivos de composição corporal.</p></article><article><span>04</span><h3>Reeducação alimentar</h3><p>Construção de autonomia e hábitos sustentáveis para o dia a dia.</p></article></div></section>
<section className="la-about la-section" id="sobre"><div className="la-about-image"><img src="/luana/luana-abreu.webp" alt="Luana Abreu, nutricionista"/><span>CRN11 20550/P</span></div><div className="la-about-copy"><p className="la-label">04 - Luana Abreu</p><h2>Cuidado próximo.<br/><em>Orientação clara.</em></h2><p>Luana Abreu é nutricionista clínica em Fortaleza. Seu atendimento considera histórico de saúde, rotina, preferências alimentares e objetivos para construir um plano realista, leve e sustentável.</p><div className="la-facts"><span>Nutrição clínica</span><span>Fortaleza - CE</span><span>Teleconsulta</span></div><a className="la-instagram" href={INSTAGRAM} target="_blank" rel="noreferrer"><Insta dark/> @luanaabreunutri</a></div></section>
<section className="la-faq la-wine"><div><p className="la-label light">05 - Antes de começar</p><h2>Perguntas<br/><em>frequentes.</em></h2></div><div className="la-faq-list"><details><summary>Como funciona a primeira consulta?<span>＋</span></summary><p>É o momento de compreender histórico de saúde, rotina, preferências, dificuldades e objetivos.</p></details><details><summary>O atendimento pode ser online?<span>＋</span></summary><p>Sim. Há atendimento presencial em Fortaleza e também por teleconsulta.</p></details><details><summary>O plano alimentar é individualizado?<span>＋</span></summary><p>Sim. A proposta considera a realidade e as preferências de cada paciente.</p></details></div></section>
<section className="la-contact la-section" id="contato"><div><p className="la-label">06 - Próximo passo</p><h2>Comece com uma escolha<br/><em>possível hoje.</em></h2></div><div className="la-card"><p>Consulte a agenda e escolha a melhor modalidade para iniciar seu acompanhamento.</p><a className="la-button la-button-wine" href={DOCTORALIA} target="_blank" rel="noreferrer">Ver agenda na Doctoralia</a><a className="la-instagram" href={INSTAGRAM} target="_blank" rel="noreferrer"><Insta dark/> @luanaabreunutri</a></div></section>
<footer className="la-footer"><img src="/luana/sublogo-gold.png" alt="Luana Abreu Nutricionista"/><p>Nutrição clínica com acolhimento,<br/>estratégia e leveza.</p><div className="la-footer-links"><Link href="/">Conhecer o Núcleo TC ↗</Link><a href={INSTAGRAM} target="_blank" rel="noreferrer"><Insta/> @luanaabreunutri</a></div><div className="la-legal"><span>© 2026 LUANA ABREU.</span><span>Conteúdo informativo. Consulte um profissional habilitado.</span><a href="https://instagram.com/felipezdog.dsgn" target="_blank" rel="noreferrer">Criado por @felipezdog.dsgn</a></div></footer>
<a className="la-whatsapp" href={WHATSAPP} target="_blank" rel="noreferrer" aria-label="Conversar sobre atendimento com Luana Abreu pelo WhatsApp"><Whats/></a>
</main>}
